name: Setup Node.js and Install Dependencies
description: Composite action to setup Node and install dependencies

inputs:
  node-version:
    description: Version of Node.js to use
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Install Dependencies
      run: npm ci
      shell: bash